### ISSUE TITLE
Consider renaming class to `layout--flex`

### ISSUE THREAD

**Issue by nenadjelovac** [csshugs/objects.flex-layout#4]
I feel that `layout--justifized` is not a perfect name (actually misleading), because items are not justified, they are "flexboxed" :) 

Flexbox items can be arranged in a lot of manners, justify is just one of them :)

**Comment by csshugs** [comment]
@nenadjelovac As mentioned [here](https://github.com/csshugs/objects.flex-layout/issues/1#issuecomment-168678461), the goal of this modifier was providing a way to have equally high layout-items despite their individual height ([see here](http://codepen.io/csshugs/pen/OVovvo) for a demo).

The name actually is quite stupid I must agree. Better would be something like `layout--equal-height` which is more descriptive but not that elegant in my opinion. 

I'm not a big fan of naming it `layout--flex` or something. That would be like naming the original method `layout--inline-block` .i.e. describing the way we achieve it with CSS rather than naming it the way of **what** we actually achieve, which is giving the layout-items the same height in this case.

@nenadjelovac @florianbouvot
So I'm open for better naming suggestions for this modifier than "`layout--equal-height`"

**Comment by csshugs** [comment]
Since I'm not very happy with this repos code at the moment (naming etc.), I'll close this for now and will come back to it, if I'll someday continue working on this idea.
